### ISSUE TITLE
Next top-level changes to the project

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#24]
1. ~~Fix top-level README.md~~
2. ~~Remove `data` directory~~
3. Explore the possibility of bring the following config files to top-level? 
   a. ~~tsconfig.json
   b. .eslintrc
   c. .eslintignore~~
   d. husky --> might require a top-level `script/git-hooks.bash` in `script`
4. Add docs/INSTALL.md

**Comment by prasadtalasila** [comment]
Add ports. env information of all the project packages here.

**Comment by prasadtalasila** [comment]
Notes on Husky:

```
We also added husky to our pipeline so it runs pre-commit and pre-push:

    Commit: Will format all ts,tsx,css,scss files with Prettier and run eslint. If eslint fails, the commit won't go through. Override in terminal with git commit -m "message" --no-verify
    Push: Will run all unittest with yarn jest . --coverage=false . If any tests fails, the push will fail. Override with in terminal HUSKY=0 git push
```

Also update codeclimate.yml to increase the duplication line threshold

**Comment by prasadtalasila** [comment]
Fix the URL for codecov in STATUS.md

**Comment by prasadtalasila** [comment]
Update docs/LIB-MS.md with config examples from PR #23

**Comment by prasadtalasila** [comment]
Rename vagrant user in [install script](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/script/install.bash) to ``$USER`

**Comment by prasadtalasila** [comment]
Deduplicate `script/install.bash` and `deploy/vagrant/make-boxes/provision.sh`. Write a shell function and place it in `script/functions.bash`. See [a good answer on stackoverflow](https://stackoverflow.com/questions/36829997/how-to-import-shell-functions-from-one-file-into-another)

**Comment by prasadtalasila** [comment]
> Notes on Husky:
> 
> ```
> We also added husky to our pipeline so it runs pre-commit and pre-push:
> 
>     Commit: Will format all ts,tsx,css,scss files with Prettier and run eslint. If eslint fails, the commit won't go through. Override in terminal with git commit -m "message" --no-verify
>     Push: Will run all unittest with yarn jest . --coverage=false . If any tests fails, the push will fail. Override with in terminal HUSKY=0 git push
> ```
> 
> ~Also update codeclimate.yml to increase the duplication line threshold~

@SyntaxXeror , there is `.husky` at the top-level of the project. Do we also need `client/.husky`?

**Comment by prasadtalasila** [comment]
Commit ade0558d57811b4d9d87dc3cdda67c7017619d80 resolves some of the issues.

**Comment by prasadtalasila** [comment]
Add `yarn build` command to docs/LIB-MS.md

**Comment by prasadtalasila** [comment]
In `deploy/vagrant/make_boxes/dtaas/README.md`, after line-19, add the following two commands:
```bash
mv key vagrant
mv key.pub vagrant.pub
```

**Comment by prasadtalasila** [comment]
Correct `build/static/env.js` in docs/CLIENT.md to `build/env.js`

**Comment by SyntaxXeror** [comment]
> 

I need @Omarley7 to answer this

**Comment by Omarley7** [comment]
> > Notes on Husky:
> > ```
> > We also added husky to our pipeline so it runs pre-commit and pre-push:
> > 
> >     Commit: Will format all ts,tsx,css,scss files with Prettier and run eslint. If eslint fails, the commit won't go through. Override in terminal with git commit -m "message" --no-verify
> >     Push: Will run all unittest with yarn jest . --coverage=false . If any tests fails, the push will fail. Override with in terminal HUSKY=0 git push
> > ```
> > ~Also update codeclimate.yml to increase the duplication line threshold~
> 
> @SyntaxXeror , there is `.husky` at the top-level of the project. Do we also need `client/.husky`?

`client/.husky` can safely be deleted. It was an implementation mistake that I made and is currently not being used. Everything is correctly handled by `<root>/.husky`. @prasadtalasila do you want me to look further into the potential need of `script/git-hooks.bash` or is that already addressed in Commit [ade0558](https://github.com/INTO-CPS-Association/DTaaS/commit/ade0558d57811b4d9d87dc3cdda67c7017619d80)?

**Comment by prasadtalasila** [comment]
The husky git hooks are currently working for client because of the husky npm package in client/package.json. Can we make husky work by putting it at the root level and still not having package.json at the root?
One obvious solution is to copy husky.sh into .husky directory. But the versioning goes out the window. Is there a better solution?

The git-hooks.bash is a good idea. We can perhaps keep them in .hooks directory and have git-hooks.bash copy them into .git/hooks on the developer machine. If this takes less than half a day, please finish it. Otherwise, let's copy husky.sh into .husky directory and move on for now. If you decide to use the husky hack, please open an issue and copy our discussion to that issue so that we don't forget it. Thanks.

**Comment by prasadtalasila** [comment]
> In `deploy/vagrant/make_boxes/dtaas/README.md`, after line-19, add the following two commands:
> 
> ```shell
> mv key vagrant
> mv key.pub vagrant.pub
> ```

done in commit 4293b8f

**Comment by Omarley7** [comment]
@prasadtalasila Sorry I missed this issue when responding in #34. I still don't fully understand what you meant by this:
> One obvious solution is to copy husky.sh into .husky directory. But the versioning goes out the window. Is there a better solution?
Why does versioning go out the window, if we move husky.sh to top level?

**Comment by prasadtalasila** [comment]
Pending Tasks:
1. `docs/INSTALL.md`. This [INSTALL wiki page](https://github.com/INTO-CPS-Association/DTaaS/wiki/INSTALL-Information) needs to be completed by everyone before we migrate the page into `docs/`.
2. Husky git hooks
3. Deduplicate script/install.bash and deploy/vagrant/make-boxes/provision.sh. Separate out the docker pull commands into a smaller shell script

**Comment by prasadtalasila** [comment]
All the changes done on release-v0.2 branch.
